# fly.toml file generated for codeday-advisors-gql on 2021-11-18T11:07:22-05:00

app = "codeday-advisors-gql"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true
