# fly.toml file generated for codeday-advisors-gql on 2023-05-24T10:03:42-07:00

app = "codeday-advisors-gql"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "sea"

[experimental]
  auto_rollback = true
